CREATE DATABASE empresaBBDD;
USE empresa;
CREATE TABLE empleados(
P_EMPLEADO INT PRIMARY KEY,
A_DEPARTAMENTO VARCHAR(45) NOT NULL,
APELLIDOS VARCHAR(200) NOT NULL,
OFICIO varchar (200) NOT NULL,
SALARIO DOUBLE NOT NULL,
COMISION DOUBLE
);
CREATE TABLE departamentos (
P_DEPARTAMENTO INT PRIMARY KEY ,
NOMBRE VARCHAR (200),
LOCALIDAD VARCHAR(200)
);

ALTER TABLE empleados
ADD CONSTRAINT FK_DEP_EMPLEADO
FOREIGN KEY (A_DEPARTAMENTO) REFERENCES departamentos(P_DEPARTAMENTO); 

INSERT INTO empleados Values ();

